### PR TITLE
Get Browser Cookies

### PR DESCRIPTION
**Pull request by davenewham**
Rough implementation of browser cookie3 for SSO sessions.

As an optional parameter now
-B firefox
-B chrome

Based on #17

### CODE REVIEW

**Comment by TimEnglart** [comment]
Thanks for the PR @davenewham. 

Your implementation looks good. I'll do a review hopefully later today because there are some thing we will probably need to discuss on how it should work. 

I'll also push my rough implementation of this on to another branch so we can compare. ([web-scrape-login](https://github.com/TimEnglart/BlackBoard-Course-Downloader/tree/web-scrape-login))

**Comment by davenewham** [comment]
Ah I wasn't aware you were also working on the same task! I tried your branch, and it worked perfectly, it is a lot more elegant than my quick hack! I do have a problem where using the -s parameter doesn't work as expected - but I think that is a problem from upstream.

As an extension, I think it would be handy to handle the error codes when trying to get that username (I had an auth 401 error as I was logged into the wrong account) but other than that, seems to work perfectly! Also, maybe only selecting the cookie we are interested in - but that of course is up to you. If you need any minor assistance I don't mind offering my time, I can sit down and actually try to do a half-decent job :)

Anyway, I appreciate the effort you put into making this project as it has helped me greatly, thank you!

**Comment by TimEnglart** [comment]
Yeah sorry about that. I wasn't planning on pushing it because the idea of using cookies is so that the person didn't need to put in a password as the issues surrounding the existing login endpoint is that it doesn't support external Oauth logins and some sites don't have the mobile endpoint active.

I still cant currently log into my learn site with the cookie method I implemented (getting 401's). So there is still a bit work to do.

Thanks for contributing. Because I'll probably take some stuff from your implementation like the CLI parameter naming which makes more sense and removes the need of inputting a browser name at runtime

**Comment by TimEnglart** [comment]
Considering there have been a few cases who have used this PR (#13) with success. LGTM

Thanks for your contribution @davenewham, saved me a lot of headaches :).

**Pull request merged**
